server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/paullee714/springcloud-config
          #username: username123
          #passphrase: userpassword123
