version: '3'

services:
  activemq:
    image: rmohr/activemq
#    image: marquesi/activemq5
    container_name: activemq
    ports:
      - "8161:8161"
      - "1883:1883"
      - "5672:5672"
      - "61613:61613"
      - "61616:61616"
      - "61614:61614"
