spring:
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      routes:
        - id: NBATEAM-SERVER
          uri: lb://NBATEAM-SERVER
          predicates:
            - Path=/team/**
            - Method=GET

        - id: PLAYER-SERVER
          uri: lb://PLAYER-SERVER
          predicates:
            - Path=/player/**
            - name: Cookie
              args:
                name: customcookie
                regexp: testcookie

server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
